CUDA_VISIBLE_DEVICES="0,1,2,3" python -m torch.distributed.launch  --nproc_per_node=4  train.py \
    --device cuda \
    --output_path output \
    --lr 3e-5 \
    --dropout 0.1 \
    --epochs 2 \
    --batch_size_train 16 \
    --batch_size_eval 64 \
    --num_workers 0 \
    --eval_step 100 \
    --max_len 64 \
    --seed 42 \
    --train_file data/wiki1m_for_simcse.txt \
    --dev_file data/stsbenchmark/sts-dev.csv \
    --test_file data/stsbenchmark/sts-test.csv \
    --pretrain_model_path princeton-nlp/unsup-simcse-bert-base-uncased \
    --pooler cls \
    --train_mode unsupervise \
    --overwrite_cache \
    --do_train \
    --do_predict \
  
